### ISSUE TITLE
Install: Updating from an older version seems not working

### ISSUE THREAD

**Issue by peppelauro** [nuvolaris/nuvolaris-bugs#11] opened 2023-09-04 17:00 UTC
This is a minor bug of course, but I want to signal the strange behaviour during the update process for future enhancement or correction.

The scenario:

- Host machine windows 11

The steps:

1. Download the 0.3.0-dev.2308261806 (from the url in the installation page: https://nuvolaris.github.io/nuvolaris/3.0.0/installation/download.html )
2. Run the msi file and installed
3. Run nuv -update
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/6519310/4edf55c9-afa0-42d4-9e68-4e04aeb185d2)

4.  It asks to download the new version manually (First strange behaviour, but ok I will continue by hand)
5. I download the new version from the link proposed: (https://github.com/nuvolaris/nuv/releases/download/0.3.0-dev.2309011658/nuv_0.3.0-dev.2309011658_amd64.msi)
6. Run the msi file and this is the results:
![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/6519310/f72cc869-bf93-4c63-b84a-dfc18f1d0fc5)

It says that a newer version is already installed but it's wrong, it cannot install the newer version on windows.

The only way is to uninstall the previous one and start with the updated msi.

That's it.

**Comment by peppelauro** [comment] 2023-09-04 17:03
Please try to not call me nitpick but...

![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/6519310/dfbb3990-9f08-46f7-bb43-04f12c533046)

Someting => Something

**Comment by msciabarra** [comment] 2023-09-04 17:55
Yes I confirm the issue, and it turns out to be a version problem.
THe version references in the documentation is  0.3.0-dev.2308261806 that is a few days old.
Current version is 0.3.0-dev.2309011658 that is a few days more recent.
The installer correctly download the newer version but fails to recognize it is newer.

The command executed is msiexec /qn /i that silently updates it.
However, it you do cd .nuv/tmp from your home and try to execute the installer with 
msiexec /i nuv.msi it tells you that the installed version is NEWER! It is not, it is older.

This is the problem to solve now...

I think the problem is in the configuration of the installer

https://github.com/nuvolaris/nuv/blob/main/bin/windows/wix.json

**Comment by msciabarra** [comment] 2023-09-04 18:08
I updated documentation to point to the latest version of the installer, in the meanwhile until we resolve versininig in windows if you uninstall the current nuv and install the latest you should have the latest version and you can proceed.

**Comment by PaoloColomb1984** [comment] 2023-09-04 19:02
For .msi installations, the "a newer version is already installed" is usually related to 'upgradecode' and 'productcode' values. Those values are defined in the .msi

**Comment by PaoloColomb1984** [comment] 2023-09-04 19:06
UpgradeCode denotes a product with different versions.

ProductCode denotes a version of a product.

For example, there is one ProductCode for Microsoft Word 2003 and a different one for Word 2007. Both Word 2003 and 2007 share the same UpgradeCode since you can upgrade from one to the other.

[MSDN section on Windows Installer](http://msdn.microsoft.com/en-us/library/aa367449(VS.85).aspx)

**Comment by peppelauro** [comment] 2023-09-04 19:56
Maybe the cause is here:

![image](https://github.com/nuvolaris/nuvolaris-bugs/assets/6519310/638612af-44b3-4753-927c-b5914650c532)

the version in the https://github.com/nuvolaris/nuv/blob/main/bin/windows/setup.cmd has a fixed value to 0.3.0, maybe the installer found it and believe that the software was already up to date.

**Comment by peppelauro** [comment] 2023-09-04 20:12
I confirm my assumption, I've tested modifing the version in the msi installer (I've used an hex editor to change the version number). If I set a version number > 0.3.0 (for example 0.3.1) the installer works.

**Comment by msciabarra** [comment] 2023-09-04 20:15
Hm........ I guess we have to change versio from 0.3.0-dev.xxxx to 3.0.xxxxx-beta... as planned

**Comment by peppelauro** [comment] 2023-09-04 20:29
Yes, I think that the xxxx number has to be part of the version, in a more semantic way...

**Comment by msciabarra** [comment] 2023-09-05 07:11
Actually the version number is supposed to satisfy the semver versioning
standard. Looks like instead the windows installer does not implement it
fully...

Michele Sciabarra | CEO

m: +44 747 984 8388
e:  ***@***.***
l:   https://linkedin.com/in/msciab
Nuvolaris Inc | 1209 Orange Street , Wilmington DE
www.nuvolaris.io   [image: linkedin icon]
<https://www.linkedin.com/company/nuvolaris-io> [image: youtube icon]
<http://bit.ly/nuvtube> [image: twitter icon]
<https://twitter.com/NuvolarisIo>

**Comment by peppelauro** [comment] 2023-09-05 07:30
Maybe you could try add the complete version to the setup. What I mean is that at the moment you use only the X.X.X, not the complete versioning number

**Comment by peppelauro** [comment] 2023-09-05 07:38
Forget what I said, MSI ProductVersion only accept numbers (3 or 4 digits blocks). But in case of 4 digits blocks windows installer it seems ignoring the 4th!

**Comment by msciabarra** [comment] 2023-09-05 08:00
Hmm you are totally right actually, I found the installer wires the version 0.3.0 it does not pass the current version. My mistake long ago actually. I am trying to fix this.

**Comment by msciabarra** [comment] 2023-09-05 19:32
Problem finally fixed in latest build and taks

**Closed as completed by msciabarra** 2023-09-05 19:32 UTC
